parameters:
#    listados.example.class: DSNEmpresas\Listados\ListadosBundle\Example

services:
#    listados.example:
#        class: %listados.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
