parameters:
#    template.example.class: DSNEmpresas\Template\TemplateBundle\Example

services:
#    template.example:
#        class: %template.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
