MediterraneoFM\MediterraneoFMBundle\Entity\Clientes:
    type: entity
    table: Clientes
    fields:
        id_cliente:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_cliente
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 35
            fixed: false
            nullable: false
        apellido:
            type: string
            length: 35
            fixed: false
            nullable: false
        direccion:
            type: string
            length: 100
            fixed: false
            nullable: true
        razon_social:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: razon_social
        comercio:
            type: string
            length: 45
            fixed: false
            nullable: true
        dni:
            type: string
            length: 10
            fixed: false
            nullable: true
        cuit:
            type: string
            length: 18
            fixed: false
            nullable: true
        email:
            type: string
            length: 255
            fixed: false
            nullable: true
        telefono_comercial:
            type: string
            length: 15
            fixed: false
            nullable: false
            column: telefono_comercial
        telefono_particular:
            type: string
            length: 15
            fixed: false
            nullable: true
            column: telefono_particular
        celular:
            type: string
            length: 18
            fixed: false
            nullable: true
        isActive:
            type: boolean
            nullable: false
            column: is_active
        iva:
            type: string
            length: 30
            fixed: false
            nullable: false
    manyToOne:
        id_agencia:
            targetEntity: Agencias
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_agencia:
                    referencedColumnName: id_agencia
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
