MediterraneoFM\MediterraneoFMBundle\Entity\Comisiones:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        descripcion:
            type: string
            length: '40'
        valor:
            type: float
    lifecycleCallbacks: {  }
