MediterraneoFM\MediterraneoFMBundle\Entity\Emisoras:
    type: entity
    table: Emisoras
    fields:
        id_emisora:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_emisora
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 35
            fixed: false
            nullable: false
        direccion:
            type: string
            length: 100
            fixed: false
            nullable: true
        telefono_comercial:
            type: string
            length: 15
            fixed: false
            nullable: false
            column: telefono_comercial
    manyToOne:
        id_ciudad:
            targetEntity: Ciudades
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_ciudad:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
