MediterraneoFM\MediterraneoFMBundle\Entity\Grillas:
    type: entity
    table: Grillas
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nro_salidas:
            type: integer
            unsigned: false
            nullable: false
            column: nro_salidas
    manyToOne:
        id_programa:
            targetEntity: Programas
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_programa:
                    referencedColumnName: id_programa
                    onDelete: CASCADE
            orphanRemoval: false
        id_tipos_menciones:
            targetEntity: TiposMenciones
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_tipos_menciones:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
