MediterraneoFM\MediterraneoFMBundle\Entity\liquidacionesMovimientos:
    type: entity
    table: liquidaciones_movimientos
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        porcentaje:
            type: float
        importeBase:
            type: float
            column: importe_base
    manyToOne:
        idOrdenpub:
            targetEntity: OrdenPub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_ordenpub:
                    referencedColumnName: id_ordenpub
                    onDelete: CASCADE
            orphanRemoval: false
        idLiquidacion:
            targetEntity: Liquidaciones
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_liquidacion:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
