MediterraneoFM\MediterraneoFMBundle\Entity\Programaciones:
    type: entity
    table: Programaciones
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 50
            fixed: false
            nullable: false
        is_active:
            type: boolean
            nullable: false
            column: is_active
    manyToOne:
        id_emisora:
            targetEntity: Emisoras
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_emisora:
                    referencedColumnName: id_emisora
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
