parameters:
#    agencias.example.class: DSNEmpresas\Agencias\AgenciasBundle\Example

services:
#    agencias.example:
#        class: %agencias.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
