parameters:
#    template_asociacion.example.class: DSNEmpresas\Template\TemplateAsociacionBundle\Example

services:
#    template_asociacion.example:
#        class: %template_asociacion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
