parameters:
#    asistentes.example.class: DSNEmpresas\AsociacionP\AsistentesBundle\Example

services:
#    asistentes.example:
#        class: %asistentes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
